---

- name: Install Sphinx package
  apt:
    name: sphinxsearch
    state: present

- name: Install additional systemd.unit file
  copy:
    src: sphinxsearch.service
    dest: /etc/systemd/systemd/sphinxsearch.service
    owner: root
    group: root
    mode: 0644
  notify: Reload demons

- name: Remove init.d file
  file:
    path: /etc/init.d/sphinxsearch
    state: absent
